### ISSUE TITLE
NonIssue Issue

### ISSUE THREAD

**Issue by eo1989** [bfredl/nvim-lanterna#1]
Firstly I want to acknowledge the work you put into the Nvim community, so thank you for that. Secondly I loved nvim-ipy. Now, I see you've had this out for a while and Ive done my best to try to reason through the code (Im a dilettante at best), but haven't the slightest clue as to how to get this to work with Jupyter/python. Could you write up a quick how-to? or maybe a quick gif/yt video? It would be greatly appreciated! ESP if this is more performant than the competition!

**Comment by bfredl** [comment]
It is not really usable as en end user product yet. but long story short `jupyter_client` broke their API so it is impossible to use with the pynvim event loop as in nvim-ipy. The lack of activity here is just because I am currently not using the jupyter ecosystem (but I expect to some time™ in the future). anyway, the code here can be forked by anyone to develop a user experience, but knowledge of how the jupyter protocol works internally is expected.
